-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.excursion
(
    id_excursion bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    price double precision,
    tour_id bigint NOT NULL,
    CONSTRAINT excursion_pkey PRIMARY KEY (id_excursion)
);

CREATE TABLE IF NOT EXISTS public.guide
(
    id_guide bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    experience integer,
    language character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    excursion_id bigint NOT NULL,
    CONSTRAINT guide_pkey PRIMARY KEY (id_guide)
);

CREATE TABLE IF NOT EXISTS public.hotel
(
    id_hotel bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    price_per_night double precision,
    stars integer,
    tour_id bigint NOT NULL,
    CONSTRAINT hotel_pkey PRIMARY KEY (id_hotel)
);

CREATE TABLE IF NOT EXISTS public.location
(
    id_location bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    city character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    excursion_id bigint NOT NULL,
    CONSTRAINT location_pkey PRIMARY KEY (id_location)
);

CREATE TABLE IF NOT EXISTS public.model_user
(
    id_user bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    active boolean NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT model_user_pkey PRIMARY KEY (id_user)
);

CREATE TABLE IF NOT EXISTS public.review
(
    id_review bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    comment character varying(255) COLLATE pg_catalog."default",
    rating integer,
    tour_id bigint NOT NULL,
    CONSTRAINT review_pkey PRIMARY KEY (id_review)
);

CREATE TABLE IF NOT EXISTS public.tour
(
    id_tour bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    duration integer,
    name character varying(255) COLLATE pg_catalog."default",
    price double precision,
    CONSTRAINT tour_pkey PRIMARY KEY (id_tour)
);

CREATE TABLE IF NOT EXISTS public.transport
(
    id_transport bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    capacity integer,
    operator character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    tour_id bigint NOT NULL,
    CONSTRAINT transport_pkey PRIMARY KEY (id_transport)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_id bigint NOT NULL,
    roles character varying(255) COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public.excursion
    ADD CONSTRAINT fkkosru7lu946uayb00vca7voj5 FOREIGN KEY (tour_id)
    REFERENCES public.tour (id_tour) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.guide
    ADD CONSTRAINT fkq7ymesu1ji2d5waumxrm7v3x2 FOREIGN KEY (excursion_id)
    REFERENCES public.excursion (id_excursion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hotel
    ADD CONSTRAINT fkjw23omxk3itr4kk4d7w41t8xy FOREIGN KEY (tour_id)
    REFERENCES public.tour (id_tour) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.location
    ADD CONSTRAINT fkq5qgvohy7adnu4rpypha101fu FOREIGN KEY (excursion_id)
    REFERENCES public.excursion (id_excursion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT fk2yxuruefnrj0xan64vi2gg7ag FOREIGN KEY (tour_id)
    REFERENCES public.tour (id_tour) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transport
    ADD CONSTRAINT fkg0dkur1sh0fdim1rdm1j4s8y5 FOREIGN KEY (tour_id)
    REFERENCES public.tour (id_tour) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fkhnk3nw6rsvkly3ww7umdq7ys1 FOREIGN KEY (user_id)
    REFERENCES public.model_user (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;